CHAT_MODEL_NAME = "gemini-3-pro-preview"
EMBEDDING_MODEL_NAME = "qwen3-embedding:0.6b"
OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_CHAT_MODEL = "minimax-m2.5"
OLLAMA_CLOUD_BASE_URL = "https://ollama.com"
